# Docker compose file for the FastAPI application
# Define compose file version -> latest is 5.5.0

services:
  # Database service using PostgreSQL
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - wed-studiozs-pgdata:/var/lib/postgresql/data
    networks:
      - wed-studiozs-pgdb
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database migration service using Python's Alembic
  db-migration:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - wed-studiozs-pgdb
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head"

  # Web service for the FastAPI application
  web:
    build:  
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: wed-studiozs-web
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - wed-studiozs
      - wed-studiozs-pgdb
    restart: unless-stopped
    depends_on:
      db-migration:
        condition: service_completed_successfully

# Networks and volumes for the services
networks:
  wed-studiozs:
    driver: bridge
  wed-studiozs-pgdb:
    driver: bridge
    internal: true
volumes:
  wed-studiozs-pgdata:


