apiVersion: v1
kind: ConfigMap
metadata:
  name: wed-studiozs-configmap
  namespace: wed-studiozs
data:
  POSTGRES_USER: "wedstudiozs"
  POSTGRES_DB: "wed-studiozs"
  POSTGRES_HOST: "postgres.wed-studiozs.svc.cluster.local"
  # Environment variables for the application
  APP_NAME: "WED STUDIOZS"
  APP_PORT: "8000"
  ENVIRONMENT: "development"
  DEBUG: "true"